#!/usr/bin/env python2
#coding:utf-8
import sys
import re

Mod = '\[[A-Za-z0-9:]{2,}[^\]]*\]'

rules = re.compile(Mod)

lrc = {}

# analyze the file.
for line in open(sys.argv[1]):
    line = line.replace('\r', '')  # Go hell the damn \r
    text = rules.split(line)
    tag = rules.findall(line)
    for a in tag:
        a = a.replace('[', '')
        a = a.replace(']', '')
        key,value = a.split(':')
        if key == 'ti':
            print "标题:", value
        elif key == 'ar':
            print "艺术家:", value
        elif key == 'al':
            print "专辑:", value
        elif key == 'by':
            print "制作:", value
        elif key == 'offset':
            print "提前量:", value, "秒"
        elif re.search('^[0-9]', a) is not None:  # yes, only time here
            Time_Mod = "[:.]"
            mm, ss, fff = re.split(Time_Mod, a)
            if len(fff) == 0:
                fff = '0'

            time = int((float("0.%s" % fff) + float(ss) + float(mm) * 60)*1000)
            lrc[time] = (mm, ss, fff, text[-1].replace('\n', ''))
        else:
            continue

# output the lyrics.
for k in sorted(lrc.keys()):
    d = lrc[k]
    print "%s:%s.%s %s" % d

